name: Build, Test & Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    # Skip job based on the commit message
    if: contains(toJson(github.event.commits), '[skip build]') == false
    name: Build, Test and Push docker image
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Output Docker info
        run: docker info
      - name: Sets build date
        run: echo "BUILD_DATE=$(date '+%Y%m%d')" >> $GITHUB_ENV
      - name: Build image
        run: make build
        env:
          VERSION: latest
      - name: Test image
        run: make test
        env:
          VERSION: latest
      - name: Docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_LOGIN}}
          DOCKER_TOKEN: ${{secrets.DOCKER_PWD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_TOKEN
      - name: Push image
        env:
          VERSION: latest
        run: |
          docker push thearqsz/wkhtmltopdf:$VERSION
